version: "3.7"

networks:
  backend_nw:
    driver: overlay
    external: true

services:
  pg_backups:
    image: akhilrs/files-backup:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
    environment:
      - SCHEDULE=@every 0h5m0s # https://godoc.org/github.com/robfig/cron#hdr-Predefined_schedules
      - BACKUP_KEEP_DAYS=1
      - BACKUP_KEEP_WEEKS=1
      - BACKUP_KEEP_MONTHS=1
      - HEALTHCHECK_PORT=80
      - CLOUD_BACKUP=True
      - CLOUD_PROVIDER=AWS  # Azure or AWS
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_SUB_FOLDER=${AWS_S3_SUB_FOLDER}
      - AWS_REGION=${AWS_REGION}
      - SOURCE_DIR=${SOURCE_DIR}
    volumes:
      - ./files-dir:/media
    networks:
      - backend_nw
